# Generated by Django 4.0.1 on 2022-01-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=500)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('item_location', models.CharField(max_length=50)),
                ('release_date', models.DateTimeField(verbose_name='release date')),
            ],
        ),
    ]
